<?php

use Symfony\Component\Yaml\Yaml;

/**
 * Implements  hook_islandora_bagger_config_file_contents_alter().
 */
function islandora_bagger_integration_islandora_bagger_config_file_contents_alter($nid, &$config_file_contents) {
 if (\Drupal::moduleHandler()->moduleExists('context')) {
   $context_manager = \Drupal::service('context.manager');
   foreach ($context_manager->getActiveReactions('islandora_bagger_integration_config_options') as $reaction) {
     // Last one wins.
     $options = $reaction->execute();
   }

   $config =  $settings = Yaml::parse($config_file_contents);
   $options_from_context = Yaml::parse($options);
   // If key exists in cofig file, update value; if not, add it as an option.
   foreach ($options_from_context as $key => $value) {
     if (in_array(trim($key), $incoming_config)) {
       $config[trim($key)] = $value;
     }
     else {
       $config[trim($key)] = $value;
     }
   }
   // Reserialize the modified YAML into $config_file_contents.
   $config_file_contents = Yaml::dump($config);
 }
}
